version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp-network

  web:
    image: 489109585245.dkr.ecr.eu-north-1.amazonaws.com/aca-wordpress:latest
    container_name: running-app
    restart: always
    ports:
      - "8080:5000"
    environment:
      WORDPRESS_DB_HOST: mysql-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    depends_on:
      - db
    networks:
      - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  mysql_data:
